accounts/urls.py
from django.urls import path

from accounts import views
from accounts.views import personal_signUp, company_signUp

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signup_personal/', views.signup_personal, name='signup_personal'),
    path('signup_company/', views.signup_company, name='signup_company'),
    path('login/', views.login, name='login'),
    path('login_wallet/', views.login_wallet, name='login_wallet'),
    path('login_personal/', views.login_personal, name='login_personal'),
    path('login_company/', views.login_company, name='login_company'),
    path('print/',personal_signUp, name='printconsole'),
    path('print2/',company_signUp,name='print2console'),
    
    path('logout/', views.logout, name='logout'),
]

resumes/urls.py
from django.urls import path

from resumes.views import ResumeCreate, ResumeDelete, ResumeUpdate, ResumeDetail, ResumeList

app_name = 'resumes'
urlpatterns = [
    path('create/', ResumeCreate.as_view(), name='resume_create'),
    path('delete/<int:pk>/', ResumeDelete.as_view(), name='resume_delete'),
    path('update/<int:pk>/',ResumeUpdate.as_view(), name='resume_update'),
    path('detail/<int:pk>',ResumeDetail.as_view(), name='resume_detail'),
    path('', ResumeList, name='resume_list'),
]

sebako/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import accounts.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', accounts.views.home, name='home'),
    path('accounts/<int:pk>/',accounts.views.detail, name='detail'),
    # path('accounts/new/', accounts.views.new, name='new'),
    # path('accounts/create/', accounts.views.create, name='create'),
    # path('index/', accounts.views.index, name='index'),
    path('singlepage/',include('singlepage.urls')),
    path('resume/', include('resumes.urls')),
    path('managepage/',include('managepage.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from datetime import datetime
from uuid import uuid4

from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.urls import reverse


# 일반회원
class Person(models.Model):
    is_user = models.BooleanField(default=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='지갑주소')
# 기업회원
class Company(models.Model):
    is_company = models.BooleanField(default=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='지갑주소')
    name = models.CharField(max_length=30, verbose_name='회사이름')
# 일반회원 프로필 - 일반회원을 외례키로 상속받음
class Profile(models.Model):
    user_id = models.ForeignKey(Person, on_delete=models.CASCADE, verbose_name='아이디', db_column='user_id')
    korName = models.CharField(max_length=30, verbose_name='한글이름')
    engName = models.CharField(max_length=30, verbose_name='영문이름')
    email = models.EmailField(max_length=50, verbose_name='이메일')
    phone = models.CharField(max_length=13, verbose_name='전화번호')

    github = models.URLField(blank=True, verbose_name='깃허브')
    blog = models.URLField(blank=True, verbose_name='블로그')
    facebook = models.URLField(blank=True, verbose_name='페이스북')
    insta = models.URLField(blank=True,verbose_name='인스타')

    created_at = models.DateField(auto_now_add=True)
    # IPFS 네트워크를 사용하여 이미지 파일을 관리
    image_hash = models.CharField(max_length=255, blank=True, null=True)
    # image = models.ImageField(upload_to='profile/images/user', blank=True, verbose_name='프로필 사진')

    def get_absolute_url(self):
        return reverse('singlepage:page_detail', args=[self.id])

    def __str__(self):
        return f'{self.user_id.user}'

class SNS(models.Model):
    user_id = models.ForeignKey(Person, on_delete=models.CASCADE)
    github = models.URLField(blank=True, verbose_name='깃허브')
    blog = models.URLField(blank=True, verbose_name='블로그')
    facebook = models.URLField(blank=True, verbose_name='페이스북')
    insta = models.URLField(blank=True,verbose_name='인스타')

    class Meta:
        verbose_name_plural = "SNS"

# class Company(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='아이디')
#     phone = models.CharField(max_length=13, verbose_name='전화번호')
#     email = models.EmailField(max_length=50, verbose_name='이메일')
#     regiNum = models.IntegerField(verbose_name='사업자번호')
#     compName = models.CharField(max_length=30, verbose_name='기관명')


def get_file_path(instance, filename):
    # 현재 날짜를 지정된 형식으로 포맷
    ymd_path = datetime.now().strftime('%Y/%m/%d')
    # 파일명을 고유한 문자열로 암호화하기 위해 사용
    uuid_name = uuid4().hex
    return '/'.join(['upload_file/',ymd_path,uuid_name])


upload_images = models.ImageField(upload_to=get_file_path, null=True, blank=True, verbose_name='프로필 사진')
filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')

resumes/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse

from accounts.models import Person


class SelfIntro(models.Model): # 간단자기소개서 작성 필드
    text = models.TextField(verbose_name='간단소개')
    # sns = models.JSONField(verbose_name='sns 종류 및 주소')
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    user = models.ForeignKey(Person, null=False, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.user}] {self.text}'

class Experience(models.Model): # 경험 작성 필드
    title = models.CharField(max_length=30, verbose_name='직무')
    company = models.CharField(max_length=30, verbose_name='회사/장소')
    text = models.TextField(verbose_name='당시 한 일')
    dateFrom = models.DateField(verbose_name='시작일')
    dateEnd = models.DateField(verbose_name='종료일')

    signature = models.CharField(max_length=10, blank=True, verbose_name='인증')
    domain = models.URLField(blank=True, verbose_name='이더넷')

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    user = models.ForeignKey(Person, null=False, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.user}] {self.title}'

class Education(models.Model): # 학력 작성 필드
    school = models.CharField(max_length=30, verbose_name='학교명')
    major = models.CharField(max_length=30, verbose_name='전공명', null=True)
    # course = models.JSONField( verbose_name='이수과목')
    dateEnd = models.DateField(verbose_name='종료일')
    GPA = models.CharField(max_length=5, verbose_name='학점')

    signature = models.CharField(max_length=10, blank=True, verbose_name='인증')
    domain = models.URLField(blank=True, verbose_name='이더넷')

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    user = models.ForeignKey(Person, null=False, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.user}] {self.school}'


class Resume(models.Model): # 자격증 작성 필드
    title = models.CharField(max_length=30, verbose_name='자격증명')
    regiNum = models.CharField(max_length=30, verbose_name='자격증번호')
    issure = models.CharField(max_length=30, verbose_name='발급처')
    dateAcq = models.DateField(verbose_name='취득일')

    signature = models.CharField(max_length=10,blank=True, verbose_name='인증')
    domain = models.URLField(blank=True, verbose_name='이더넷')

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    user = models.ForeignKey(Person, null=False, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.user}] {self.title}'

    def get_absolute_url(self):
        return reverse('resumes:resume_detail', args=[self.id])

    class Meta:
        ordering = ['-created_at']

accounts/forms.py
from django import forms

from accounts.models import Person, Company


class personForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['user']

class companyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['user']

accounts/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

# Create your views here.
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from accounts.forms import personForm
from accounts.models import Profile, Person, SNS, Company

# 메인페이지
def home(request):
    return render(request, 'accounts/home2.html')
    # return render(request, 'zzsignup.html')


def detail(request, pk):
    # blog_detail = get_object_or_404(Blog, pk=pk)
    return render(request, 'accounts/detail.html')


def index(request):
    return render(request, 'accounts/index.html')

# 회원가입 페이지
def signup(request):
    return render(request, 'accounts/signup.html')

# ID,PW를 통한 기업 회원가입
def signup_company(request):
    if request.method == 'POST':
        if User.objects.filter(username=request.POST['username']).exists():
            messages.info(request, '이미 가입한 아이디입니다')
            return redirect('accounts:signup_personal')
        # redirect는 함수 명 적어.

        if request.POST['password1'] == request.POST['password2']:
            if len(request.POST['password1']) < 8:
                messages.info(request, '비밀 짧아')
                return redirect('accounts:signup_personal')

            user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password1'],
            )
            # korName = '한국'
            # engName = 'Engl'
            # address = 'bababobo'
            # email = 'babo@babo.com'
            # phone = '010-5123-4567'
            korName = request.POST['korName']
            engName = request.POST['engName']
            address = request.POST['Address']
            email = request.POST['EmailId'] + '@' + request.POST['EmailDomain']
            phone = request.POST['Phone1'] + '-' + request.POST['Phone2'] + '-' + request.POST['Phone3']
            # sns = request.POST['GitSns']

            profile = Profile(user=user, korName=korName, engName=engName, address=address, email=email, phone=phone)
            profile.save()
            auth.login(request, user)
            return redirect('home')

        return render(request, 'accounts/signup_personal.html')
    return render(request, 'accounts/signup_company.html')

# ID,PW를 통한 개인 회원가입
def signup_personal(request):
    if request.method == 'POST':
        if User.objects.filter(username=request.POST['username']).exists():
            messages.info(request, '이미 가입한 아이디입니다')
            return redirect('accounts:signup_personal')
        # redirect는 함수 명 적어.

        if request.POST['password1'] == request.POST['password2']:
            if len(request.POST['password1']) < 8:
                messages.info(request, '비밀 짧아')
                return redirect('accounts:signup_personal')

            user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password1'],
            )
            # korName = '한국'
            # engName = 'Engl'
            # address = 'bababobo'
            # email = 'babo@babo.com'
            # phone = '010-5123-4567'
            korName = request.POST['korName']
            engName = request.POST['engName']
            address = request.POST['Address']
            email = request.POST['EmailId'] + '@' + request.POST['EmailDomain']
            phone = request.POST['Phone1'] + '-' + request.POST['Phone2'] + '-' + request.POST['Phone3']
            # sns = request.POST['GitSns']

            profile = Profile(user=user, korName=korName, engName=engName, address=address, email=email, phone=phone)
            profile.save()
            auth.login(request, user)
            return redirect('home')

        return render(request, 'accounts/signup_personal.html')
    return render(request, 'accounts/signup_personal.html')

# ID,PW를 통한 로그인
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('singlepage:page_detail', user.person.pk)
        else:
            return render(request, 'accounts/login.html', {'error': 'username or password is incorrect'})

    else:
        return render(request, 'accounts/login.html')


def login_personal(request):
    if request.user.is_authenticated:
        return redirect('home')

    return render(request, 'accounts/login_personal.html')


def login_company(request):
    if request.user.is_authenticated:
        return redirect('home')

    return render(request, 'accounts/login_company.html')

# 기본 제공 로그아웃
def logout(request):
    auth.logout(request)
    return redirect('home')

# web3 모듈을 통해 지갑아이디로 일반회원 회원가입
def personal_signUp(request):
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        print(request.POST['walletAddress'])
        print(request.POST['walletAddress'])
        user = User.objects.create_user(
            username=request.POST['walletAddress']
        )
        person = Person(user=user)
        person.save()

        profile = Profile(user_id=person)
        sns = SNS(user_id=person)
        sns.save()
        profile.save()
        auth.login(request, user)
        return redirect('singlepage:page_detail', user.person.pk)
    else:
        print('why no')
        print('why no')
        print('why no')
        render(request, 'accounts/signup.html')

def company_signUp(request):
    if request.user.is_authenticated:
        return redirect('home')

    username = request.POST['walletAddress']
    compName = request.POST['compName']
    user = User.objects.create_user(
        username=username
    )
    company = Company(user=user,
                      name=compName)
    company.save()
    messages = company
    context = {
        'message':messages
    }
    return HttpResponse(status=201)

# web3 모듈을 통해 지갑아이디로 통한 로그인
def login_wallet(request):
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        username = request.POST['walletAddress']

        try:
            if User.objects.get(username=username):
                print(username)
                print(username)
                print(username)
                user = User.objects.get(username=username)

                auth.login(request,user)
                return redirect('home')

        except:
            messages.info(request,'회원가입을 먼저 진행해주세요')
            return render(request,'accounts/login.html',{'error': 'WalletAccount is incorrect'})

    else:
        return render(request, 'accounts/login.html')

resumes/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from accounts.models import SNS
from resumes.models import Resume


def ResumeList(request): # 가장 메인에 보여줄 로직
    # model = Resume
    # template_name_suffix = '_list'
    resumes = Resume.objects.all()
    return render(request,'resumes/resume_list.html',{'objects':resumes})

class ResumeCreate(CreateView): # 자격증 생성할때 사용,채워야할 필드 확인, 이후에 연결될 탬플릿 이름은 resume_create일것
    model = Resume
    fields = ['title','regiNum','issure','dateAcq','file_upload']
    # template_name = 'resumes/resume_create.html'
    template_name_suffix = '_create'
    success_url = '/index'

    def form_valid(self, form):
        # 작성자는 현재 로그인 한 사용자로 설정함
        form.instance.user_id = self.request.user.id
        if form.is_valid():
            # 올바르다면 form : 모델폼
            form.instance.save()
            return redirect('/')
        else:
            # 올바르지 않다면
            return self.render_to_response({'form': form})

class ResumeUpdate(UpdateView):
    model = Resume
    # template_name = 'resumes/resume_update.html'
    fields = ['title','regiNum','issure','dateAcq', 'file_upload']
    template_name_suffix = '_update'
    success_url = '/resume/'

class ResumeDelete(DeleteView):
    model = Resume
    # template_name = 'resumes/resume_delete.html'
    template_name_suffix = '_delete'
    success_url = '/index'

class ResumeDetail(DetailView):
    model = Resume
    # template_name = 'resumes/resume_detail.html'
    template_name_suffix = '_detail'

templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
    <meta name="description" content="" />
    <meta name="author" content="" />
    {% if user.is_authenticated %}
    <script type="text/javascript">
      window.location.href = '{% url 'home' %}';
    </script>
    {% endif %}
    <title>SEBAKO-로그인</title>
    <script
      src="https://use.fontawesome.com/releases/v5.15.3/js/all.js"
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <link rel="preconnect" href="https://fonts.gstatic.com"> 
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700&display=swap" rel="stylesheet">
    <!-- Third party plugin CSS-->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css"
      rel="stylesheet"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/stylesHome.css' %}" rel="stylesheet" />
    <link href="{% static 'css/util.css' %}" rel="stylesheet" />
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
  </head>

  <body id="page-top">
    <nav
      class="navbar navbar-expand-lg navbar-light fixed-top py-3"
      id="mainNav"
      style="background-color: white"
    >
      <div class="container">
        <a
          class="navbar-brand js-scroll-trigger"
          href="/"
          style="font-size: 27px; color: black"
        >
          S E B A K O</a
        >
        <button
          class="navbar-toggler navbar-toggler-right"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto my-2 my-lg-0">
            <li class="nav-item">
              <a
                class="nav-link js-scroll-trigger"
                href="/#about"
                style="
                  font-family: 'Noto Sans KR', sans-serif;
                  font-weight: 500;
                  font-size: 20px;
                  color: black;
                "
                onmouseover = "this.style.color='#00A0E2'"
                onmouseout  = "this.style.color='black'"

              >
                About</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link js-scroll-trigger"
                href="/#services"
                style="
                  font-family: 'Noto Sans KR', sans-serif;
                  font-weight: 500;
                  font-size: 20px;
                  color: black;
                "
                onmouseover = "this.style.color='#00A0E2'"
                onmouseout  = "this.style.color='black'"
              >
                Services</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link js-scroll-trigger"
                href="/#contact"
                style="
                  font-family: 'Noto Sans KR', sans-serif;
                  font-weight: 500;
                  font-size: 20px;
                  color: black;
                "
                onmouseover = "this.style.color='#00A0E2'"
                onmouseout  = "this.style.color='black'"
              >
                Contact</a
              >
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a
                class="nav-link js-scroll-trigger"
                href="/accounts/logout"
                style="
                  font-family: 'Noto Sans KR', sans-serif;
                  font-weight: 500;
                  font-size: 20px;
                  color: black;
                "
                onmouseover = "this.style.color='#00A0E2'"
                onmouseout  = "this.style.color='black'"
              >
                로그아웃</a
              >
            </li>
            {% if user.person.is_user %}
            <li class="nav-item">
              <a
                class="nav-link js-scroll-trigger"
                href="/singlepage/{{user.person.pk}}/"
                style="
                  font-family: 'Noto Sans KR', sans-serif;
                  font-weight: 500;
                  font-size: 20px;
                  color: black;
                "
                onmouseover = "this.style.color='#00A0E2'"
                onmouseout  = "this.style.color='black'"
              >
                내 정보</a
              >
            </li>
            {% else %}
            <li class="nav-item">
              <a
                class="nav-link js-scroll-trigger"
                href="/singlepage/{{user.profile.pk}}/"
                style="
                  font-family: 'Noto Sans KR', sans-serif;
                  font-weight: 500;
                  font-size: 20px;
                  color: black;
                "
                onmouseover = "this.style.color='#00A0E2'"
                onmouseout  = "this.style.color='black'"
              >
                인증관리</a
              >
            </li>
            {% endif %} {% else %}
            <li class="nav-item">
              <a
                class="nav-link js-scroll-trigger"
                href="{% url 'accounts:signup' %}"
                style="
                  font-family: 'Noto Sans KR', sans-serif;
                  font-weight: 500;
                  font-size: 20px;
                  color: black;
                "
                onmouseover = "this.style.color='#00A0E2'"
                onmouseout  = "this.style.color='black'"
              >
                회원가입</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
<!--NAV END-->
    <section class="page-section bg-info" id="about">
      <div class="limiter" style="margin-top: -80px">
        <div class="container-login100">
          <div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
            <form
              method="POST"
              action="{% url 'accounts:login_wallet' %}"
              class="login100-form validate-form flex-sb flex-w"
            > {% if messages %}
              {% for message in messages %}
              <span class="login100-form-title p-b-53">{{message}}</span>
              {% endfor %}
              {% else %}
              <span class="login100-form-title p-b-53"> LOGIN </span>
              {% endif %}


              <button
                type="button"
                class="enableEthereumButton btn-face m-b-20" style="margin-left: 25%; margin-top: -20px;"
              >
                ETH 개인주소 조회
              </button>

<!--              <a-->
<!--                href="{% url 'accounts:login_company'%}"-->
<!--                class="btn-face m-b-20"-->
<!--              >-->
<!--                기업 회원-->
<!--              </a>-->

              <div class="p-t-31 p-b-9">

                <button
                  type="button"
                  class="enableEthereumButton txt2 bo1 m-l-5"
                ></button>
              </div>
              <div
                class="wrap-input100 validate-input"
                data-validate="ID is required"
              >
                {% csrf_token %}
                <input
                  class="input100"
                  name="walletAddress"
                  id="showAccount"
                  type="text"
                  readonly
                />

                <span class="focus-input100"></span>
              </div>

              <div class="container-login100-form-btn m-t-17">
                <input type="submit" class="login100-form-btn" value="로그인" />
              </div>
            </form>

            <div class="w-full text-center p-t-55">
              <span class="txt2"> 아직 회원이 아니신가요? </span>&nbsp;

              <a href="{% url 'accounts:signup' %}" class="txt2 bo1">
                회원가입
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- Footer-->
    <footer class="bg-light">
      <div class="container">
        <div class="small text-center text-muted">
          Copyright &copy;2021- SEBAKO
        </div>
      </div>
    </footer>

    <!--web3 JS-->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/gh/ethereum/web3.js@1.0.0-beta.36/dist/web3.min.js"
      integrity="sha256-nWBTbvxhJgjslRyuAKJHK+XcZPlCnmIAAMixz6EefVk="
      crossorigin="anonymous"
    ></script>

    <script src="{% static 'js/web3auth.js' %}"></script>
    <!-- Bootstrap core JS-->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/accounts/signup_error.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
    <h1>이미 가입한 아이디입니다.</h1>
</body>
</html>

templates/accounts/zzlogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SEBACO-로그인</title>
    <script type="text/javascript">

        function login(){
           alert("환영합니다.")
      }
    </script>
</head>
<body>
    <center><h1>SEBACO RESUME MANAGEMENT SYSTEM</h1></center>
    <hr>
    <div align="right">  
        
        <a href="main.html">HOME</a>
    </div>
    <br>
    
    <div align="center">
        <h2>회원 구분 로그인</h2>
    
        <br>
<!-- 개인이랑 기업 구분해서 로그인 구현_ 이 페이지에서 개인과 기업 선택 -->
    <form>
       
        
        <button type="button" onclick="location.href='login_personal.html'">개인 회원</button>
        <button type="button" onclick="location.href='login_company.html'">기업 회원</button>

    </form>
    </div>
</body>
</html>