resumes/urls.py
from django.urls import path

from resumes.views import ResumeCreate, ResumeDelete, ResumeUpdate, ResumeDetail, ResumeList

app_name = 'resumes'
urlpatterns = [
    path('create/', ResumeCreate.as_view(), name='resume_create'),
    path('delete/<int:pk>/', ResumeDelete.as_view(), name='resume_delete'),
    path('update/<int:pk>/',ResumeUpdate.as_view(), name='resume_update'),
    path('detail/<int:pk>',ResumeDetail.as_view(), name='resume_detail'),
    path('', ResumeList, name='resume_list'),
]

sebako/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import accounts.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', accounts.views.home, name='home'),
    path('accounts/<int:pk>/',accounts.views.detail, name='detail'),
    # path('accounts/new/', accounts.views.new, name='new'),
    # path('accounts/create/', accounts.views.create, name='create'),
    # path('index/', accounts.views.index, name='index'),
    path('singlepage/',include('singlepage.urls')),
    path('resume/', include('resumes.urls')),
    path('managepage/',include('managepage.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resumes/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse

from accounts.models import Person


class SelfIntro(models.Model): # 간단자기소개서 작성 필드
    text = models.TextField(verbose_name='간단소개')
    # sns = models.JSONField(verbose_name='sns 종류 및 주소')
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    user = models.ForeignKey(Person, null=False, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.user}] {self.text}'

class Experience(models.Model): # 경험 작성 필드
    title = models.CharField(max_length=30, verbose_name='직무')
    company = models.CharField(max_length=30, verbose_name='회사/장소')
    text = models.TextField(verbose_name='당시 한 일')
    dateFrom = models.DateField(verbose_name='시작일')
    dateEnd = models.DateField(verbose_name='종료일')

    signature = models.CharField(max_length=10, blank=True, verbose_name='인증')
    domain = models.URLField(blank=True, verbose_name='이더넷')

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    user = models.ForeignKey(Person, null=False, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.user}] {self.title}'

class Education(models.Model): # 학력 작성 필드
    school = models.CharField(max_length=30, verbose_name='학교명')
    major = models.CharField(max_length=30, verbose_name='전공명', null=True)
    # course = models.JSONField( verbose_name='이수과목')
    dateEnd = models.DateField(verbose_name='종료일')
    GPA = models.CharField(max_length=5, verbose_name='학점')

    signature = models.CharField(max_length=10, blank=True, verbose_name='인증')
    domain = models.URLField(blank=True, verbose_name='이더넷')

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    user = models.ForeignKey(Person, null=False, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.user}] {self.school}'


class Resume(models.Model): # 자격증 작성 필드
    title = models.CharField(max_length=30, verbose_name='자격증명')
    regiNum = models.CharField(max_length=30, verbose_name='자격증번호')
    issure = models.CharField(max_length=30, verbose_name='발급처')
    dateAcq = models.DateField(verbose_name='취득일')

    signature = models.CharField(max_length=10,blank=True, verbose_name='인증')
    domain = models.URLField(blank=True, verbose_name='이더넷')

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    user = models.ForeignKey(Person, null=False, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.user}] {self.title}'

    def get_absolute_url(self):
        return reverse('resumes:resume_detail', args=[self.id])

    class Meta:
        ordering = ['-created_at']

resumes/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from accounts.models import SNS
from resumes.models import Resume


def ResumeList(request): # 가장 메인에 보여줄 로직
    # model = Resume
    # template_name_suffix = '_list'
    resumes = Resume.objects.all()
    return render(request,'resumes/resume_list.html',{'objects':resumes})

class ResumeCreate(CreateView): # 자격증 생성할때 사용,채워야할 필드 확인, 이후에 연결될 탬플릿 이름은 resume_create일것
    model = Resume
    fields = ['title','regiNum','issure','dateAcq','file_upload']
    # template_name = 'resumes/resume_create.html'
    template_name_suffix = '_create'
    success_url = '/index'

    def form_valid(self, form):
        # 작성자는 현재 로그인 한 사용자로 설정함
        form.instance.user_id = self.request.user.id
        if form.is_valid():
            # 올바르다면 form : 모델폼
            form.instance.save()
            return redirect('/')
        else:
            # 올바르지 않다면
            return self.render_to_response({'form': form})

class ResumeUpdate(UpdateView):
    model = Resume
    # template_name = 'resumes/resume_update.html'
    fields = ['title','regiNum','issure','dateAcq', 'file_upload']
    template_name_suffix = '_update'
    success_url = '/resume/'

class ResumeDelete(DeleteView):
    model = Resume
    # template_name = 'resumes/resume_delete.html'
    template_name_suffix = '_delete'
    success_url = '/index'

class ResumeDetail(DetailView):
    model = Resume
    # template_name = 'resumes/resume_detail.html'
    template_name_suffix = '_detail'

templates/resumes/resume.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'resume:index' %}">자격증 홈</a>
<a href="{% url 'resume:craete %}">자격증 올리기</a>
</body>
</html>

templates/resumes/resume_create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        {% if user.is_active %}
        <div class="alert alert-primary" role="alert">
            모든 부분을 다 채워주세요!!
        </div>
<!--        enctype을 설정하여야 파일을 주고받을 수 있음-->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}
            <input type="submit" value="제출하기" class="btn btn-primary">
        </form>
        {% else %}
        <p>로그인 해야 보이게할거임</p>
        {% endif %}
    </div>
    <div class="col"></div>
</div>
</body>
</html>

templates/resumes/resume_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--진짜 지울건지 확인을 받아야 함. form을 또 보여줄 필요가 없음-->
<div class="alert alert-primary" role="alert">
    진짜로 {{object}}를 지우실 건가요??
</div>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제하기">
</form>
</body>
</html>

templates/resumes/resume_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-4">
        <div class="card" style="width : 30rem;">
            <div class="resume-body">
                <h5 class="resume-title">{{object.title}}</h5>
                <p class="resume-text">{{object.regiNum}}</p>
                <p class="resume-text">{{object.issure}}</p>
                <p class="resume-text">{{object.dataAcq}}</p>

            </div>

            <ul class="list-group list-group-flush">
                <li class="list-group-item">생성일 : {{object.created_at}}</li>
                <li class="list-group-item">수정일 : {{objcet.updated_at}}</li>
            </ul>

            <div class="resume-body">
                <a href="{% url 'resumes:update' object.id %}" class="resume-link">수정하기</a>
                <a href="{% url 'resumes:delete' object.id %}" class="resume-link">삭제하기</a>
            </div>
        </div>
    </div>

    <div class="col"></div>
</div>
</body>
</html>

templates/resumes/resume_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>이곳은 자격증 리스트 뷰입니다</p>

<!--{{ object.'title','regiNum','issure','dateAcq'-->
<div class="col"></div>
<div class="col-5">
    {% for resume in objects %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <p>자격증명 : {{ resume.title }}</p>
            <p>자격증번호 : {{ resume.regiNum }}</p>
            <p>발급처 : {{ resume.issure }}</p>
            <p>취득일 : {{ resume.dateAcq }}</p>

            <p>생성일 : {{ resume.created_at }}</p>
            <p>수정일 : {{ resume.updated_at }}</p>
<!--            url.py 에 app_name부분 이 url '이름: ' 이름부분-->
<!--            pk값은 views에서 넘겨준 값, 위 for 문안에 선언한 변수명의 id로 받아오겠다는 뜻-->
            <a href="{% url 'resumes:resume_delete' pk=resume.id %}" class="btn btn-outline-danger btn-sm float-right">삭제하기</a>
            <a href="{% url 'resumes:resume_update' pk=resume.id %}" class="btn btn-outline-danger btn-sm float-right">수정하기</a>
        </div>
        {% endfor %}
    </div>


</body>
</html>

templates/resumes/resume_update.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="수정하기" class="btn btn-primary">
        </form>
    </div>
    <div class="col"></div>
</div>
</body>
</html>